import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';

import docsConfig from '../../docs.config.json' with { type: 'json' };
import { SPEC } from '../../src/data/spec.generated.ts';

const repoRoot = path.resolve(import.meta.dirname, '../..');

test('pillar and level overview pages are backed by the rule catalog', () => {
  const byKey = new Map(docsConfig.docs.map((entry) => [entry.key, entry]));

  assert.deepEqual(byKey.get('pillars')?.source, {
    repo: 'spec',
    path: 'AI-CONTRIBUTOR-RULE-CATALOG.json',
  });
  assert.deepEqual(byKey.get('ref-levels')?.source, {
    repo: 'spec',
    path: 'AI-CONTRIBUTOR-RULE-CATALOG.json',
  });
});

test('generated spec data carries catalog pillar descriptions', () => {
  assert.equal(SPEC.pillars.length, 7);
  assert.ok(
    SPEC.pillars.every((pillar) => typeof pillar.description === 'string' && pillar.description),
  );
});

test('generated spec data derives clause anchors from stable clause fields', () => {
  assert.equal(SPEC.clauses[0].anchor, 'p01-c1-reproducible-environment');
  assert.equal(
    SPEC.clauses.find((clause) => clause.num === 5)?.anchor,
    'p02-c1-secrets-and-credentials',
  );
  assert.equal(
    SPEC.clauses.find((clause) => clause.num === 10)?.anchor,
    'p03-c1-runtime-validation-and-invariants',
  );
  assert.ok(SPEC.clauses.every((clause) => typeof clause.anchor === 'string' && clause.anchor));
  assert.equal(new Set(SPEC.clauses.map((clause) => clause.anchor)).size, SPEC.clauses.length);
});

test('spec-backed presentation pages load canonical data instead of inline catalogs', async () => {
  const byKey = new Map(docsConfig.docs.map((entry) => [entry.key, entry]));
  const pages = {
    pillars: await readFile(path.join(repoRoot, 'src/content/docs/docs/pillars.mdx'), 'utf8'),
    levels: await readFile(
      path.join(repoRoot, 'src/content/docs/docs/conformance-levels.mdx'),
      'utf8',
    ),
    quickstart: await readFile(path.join(repoRoot, 'src/content/docs/docs/quickstart.md'), 'utf8'),
    stampedAudit: await readFile(
      path.join(repoRoot, 'src/content/docs/docs/stamped-audit.mdx'),
      'utf8',
    ),
    ruleCatalog: await readFile(
      path.join(repoRoot, 'src/content/docs/docs/rule-catalog.mdx'),
      'utf8',
    ),
    coverageMap: await readFile(
      path.join(repoRoot, 'src/content/docs/docs/coverage-map.mdx'),
      'utf8',
    ),
  };

  assert.match(pages.pillars, /SPEC\.pillars\.map/);
  assert.match(pages.pillars, /SPEC\.clauses\.filter/);
  assert.doesNotMatch(pages.pillars, /Engineering Foundation|Quality & Reliability/);

  assert.match(pages.levels, /SPEC\.levels/);
  assert.match(pages.levels, /SPEC\.clauses\.flatMap/);
  assert.doesNotMatch(pages.levels, /Baseline Hygiene|AI Autonomous/);

  assert.deepEqual(byKey.get('quickstart')?.source, { repo: 'spec', path: 'README.md' });
  // After the Path A migration the quickstart page is the porter-emitted
  // README slice; the marker comment confirms it.
  assert.match(pages.quickstart, /generated by scripts\/spec-content\.mjs/);

  assert.deepEqual(byKey.get('stamped-audit')?.source, {
    repo: 'spec',
    path: 'AI-CONTRIBUTOR-AUDIT.md',
  });
  assert.deepEqual(byKey.get('stamped-audit')?.sourceInputs, [
    {
      repo: 'spec',
      path: 'AI-CONTRIBUTOR-AUDIT.md',
      role: 'root summary',
    },
    {
      repo: 'spec',
      path: '.ai-contributor-audit/AI-CONTRIBUTOR-CHECKLIST.md',
      role: 'checklist',
    },
    {
      repo: 'spec',
      path: '.ai-contributor-audit/AI-CONTRIBUTOR-AUDIT-LOG.md',
      role: 'audit log',
    },
  ]);
  assert.match(pages.stampedAudit, /loadSpecAuditArtifacts/);

  assert.deepEqual(byKey.get('rule-catalog')?.sourceInputs, [
    {
      repo: 'spec',
      path: 'AI-CONTRIBUTOR-RULE-CATALOG.json',
      role: 'rule data',
    },
    {
      repo: 'spec',
      path: 'docs/RULE-CATALOG-FORMAT.md',
      role: 'format prose',
    },
  ]);
  assert.match(pages.ruleCatalog, /RuleCatalogBrowser/);
  assert.deepEqual(byKey.get('coverage-map')?.sourceInputs, [
    {
      repo: 'spec',
      path: 'AI-CONTRIBUTOR-COVERAGE.md',
      role: 'coverage prose',
    },
    {
      repo: 'spec',
      path: 'AI-CONTRIBUTOR-RULE-CATALOG.json',
      role: 'coverage data',
    },
  ]);
  assert.match(pages.coverageMap, /generatedSpec.*ai-contributor-coverage/);
});

test('full specification records both prose and rule catalog provenance', () => {
  const byKey = new Map(docsConfig.docs.map((entry) => [entry.key, entry]));

  assert.deepEqual(byKey.get('spec')?.sourceInputs, [
    {
      repo: 'spec',
      path: 'AI-CONTRIBUTOR-SPECIFICATION.md',
      role: 'canonical prose',
    },
    {
      repo: 'spec',
      path: 'AI-CONTRIBUTOR-RULE-CATALOG.json',
      role: 'rule data',
    },
  ]);
});
